export const INITIAL_PRODUCTS = [
  {
    id: 'prod-1',
    _id: 'prod-1',
    title: 'Next.js 15 Full-Stack E-Commerce Template',
    slug: 'nextjs-15-ecommerce-kit',
    description: 'Complete assignment starter kit built with Next.js App Router, Tailwind CSS v4, MongoDB Mongoose models, and Stripe Checkout integration.',
    price: 49.99,
    category: 'full-stack-kits',
    rating: 4.9,
    reviewsCount: 28,
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    featured: true,
    tags: ['Next.js', 'App Router', 'MongoDB', 'Stripe', 'Tailwind'],
    downloadUrl: '/downloads/nextjs-ecommerce-kit.zip'
  },
  {
    id: 'prod-2',
    _id: 'prod-2',
    title: 'Node.js & MongoDB REST API Boilerplate',
    slug: 'nodejs-mongodb-rest-api',
    description: 'Modular Node.js Express server with Mongoose schemas, JWT authentication, role-based access control, and Stripe payment webhooks.',
    price: 29.99,
    category: 'web-templates',
    rating: 4.8,
    reviewsCount: 19,
    image: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=800&q=80',
    featured: true,
    tags: ['Node.js', 'Express', 'MongoDB', 'Mongoose'],
    downloadUrl: '/downloads/nodejs-rest-api.zip'
  },
  {
    id: 'prod-3',
    _id: 'prod-3',
    title: 'Tailwind CSS UI Component Suite',
    slug: 'tailwind-css-ui-suite',
    description: 'Over 50+ accessible, responsive React & Next.js components styled with Tailwind CSS, including dark mode, glassmorphism, and smooth animations.',
    price: 19.99,
    category: 'ui-components',
    rating: 4.9,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    featured: true,
    tags: ['Tailwind', 'React', 'UI Components', 'JSX'],
    downloadUrl: '/downloads/tailwind-components.zip'
  },
  {
    id: 'prod-4',
    _id: 'prod-4',
    title: 'Stripe Payment Gateway Integration Module',
    slug: 'stripe-payment-integration-module',
    description: 'Plug-and-play Stripe payment processing route handlers for Next.js App Router with test mode card simulator and receipt generator.',
    price: 14.99,
    category: 'assignment-projects',
    rating: 4.7,
    reviewsCount: 15,
    image: 'https://images.unsplash.com/photo-1556742049-0a67dd38805f?auto=format&fit=crop&w=800&q=80',
    featured: false,
    tags: ['Stripe', 'Node.js', 'Payments', 'JavaScript'],
    downloadUrl: '/downloads/stripe-module.zip'
  },
  {
    id: 'prod-5',
    _id: 'prod-5',
    title: 'University Full-Stack Assignment Bundle',
    slug: 'fullstack-assignment-bundle',
    description: 'Complete university assignment project package featuring documentation, database diagrams, API specs, and clean JavaScript JSX codebase.',
    price: 39.99,
    category: 'assignment-projects',
    rating: 5.0,
    reviewsCount: 31,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    featured: true,
    tags: ['Assignment', 'Full-Stack', 'Documentation', 'Next.js'],
    downloadUrl: '/downloads/assignment-bundle.zip'
  },
  {
    id: 'prod-6',
    _id: 'prod-6',
    title: 'Full-Stack Web Development Mentorship & Review',
    slug: 'web-dev-mentorship',
    description: '1-on-1 code review, MongoDB architecture guidance, and Next.js deployment assistance for students and developers.',
    price: 59.99,
    category: 'services',
    rating: 4.9,
    reviewsCount: 22,
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    featured: false,
    tags: ['Services', 'Mentorship', 'Code Review', 'Node.js'],
    downloadUrl: '/downloads/mentorship-session.pdf'
  }
];
